name: Test Runner

on:
  push:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: echo "Running on EC2 Self Hosted Runner"
